USE [master]
GO

/****** Object:  Database [AlgoTraderDb]    Script Date: 6/9/2013 11:17:40 AM ******/
CREATE DATABASE [AlgoTraderDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AlgoTraderDb', FILENAME = N'D:\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\AlgoTraderDb.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AlgoTraderDb_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\AlgoTraderDb_log.ldf' , SIZE = 784KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AlgoTraderDb] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AlgoTraderDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AlgoTraderDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AlgoTraderDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AlgoTraderDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AlgoTraderDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [AlgoTraderDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AlgoTraderDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET RECOVERY FULL 
GO

ALTER DATABASE [AlgoTraderDb] SET  MULTI_USER 
GO

ALTER DATABASE [AlgoTraderDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AlgoTraderDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AlgoTraderDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AlgoTraderDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AlgoTraderDb] SET  READ_WRITE 
GO


