/****** Object:  Table [dbo].[WatchLists]    Script Date: 6/10/2013 1:36:34 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WatchLists](
	[ListName] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_dbo.WatchLists] PRIMARY KEY CLUSTERED 
(
	[ListName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


